#ifndef PLAYER_STATES_H
#define PLAYER_STATES_H

enum PLAYER_ACTION
{
    PLAYER_IS_STILL = 1,
    PLAYER_IS_KICKING = 2,
    PLAYER_IS_RUNNING = 3,
    PLAYER_IS_RECOVERING = 4
};

#endif // PLAYER_STATES_H
